### ISSUE TITLE
Tippfehler im zweiten Absatz

### ISSUE THREAD

**Issue by nefertari1976** [Diadochokinetic/fremtpl#1]
Im zweiten Absatz ist ein Tippfehler:

Alternativ kann auch eine eigene Jupyter-Umgebung mit den in requirements.txt hinterlegten Abhängigkeiten genutzt werden. Der grundlegende Aufbau wurde **inspieriert** (inspiriert wäre richtig) durch das scikit-learn Tutorial [Tweedie regression on insurance claims](https://scikit-learn.org/stable/auto_examples/linear_model/plot_tweedie_regression_insurance_claims.html).

**Comment by Diadochokinetic** [comment]
Wurde korrigiert. Danke!
